# Deployment configuration for Bothive website
deployment:
  tasks:
    # Live folder
    - export DEPLOYPATH=/home2/winzonep/PlayVora

    # Sync repo to live folder
    - /usr/bin/rsync -av --delete \
        --exclude='.git' \
        --exclude='.cpanel.yml' \
        ./ $DEPLOYPATH